/**
 * Public gallery (/gallery) — the park in the client's OWN photography, with
 * one clean entry to the walk-through (the existing /map 3D + map).
 *
 * The gallery's whole job is to show the place, so the honesty rules are the
 * content rules:
 *  · every image here is client material already in public/media (the two real
 *    park photographs, the uploaded viewing photo, the client sheet's sample
 *    set-ups, the client masterplan) — nothing is borrowed and no stock photo
 *    is published as if it were the park;
 *  · the sheet's sample photographs keep the exact label the services page
 *    uses (`CHAPEL_SAMPLE_NOTE` / `SERVICE_SAMPLE_NOTE`) — "illustration
 *    purposes only", never a claim about a named room or a fixed set-up;
 *  · the masterplan is captioned as a drawing, not a photograph.
 *
 * Files under public/media/gallery/ are generated by
 * scripts/build-gallery-images.mjs (WebP, fixed 1×/2× widths, 3:2 card crops).
 * The explicit `width`/`height` pairs are the published pixels, so the cards
 * reserve their space and the page never shifts while the photos load.
 */
import { CHAPEL_SAMPLE_NOTE, SERVICE_SAMPLE_NOTE } from "@/lib/media";

export type GalleryPhoto = {
  /** 1× source the layout uses by default. */
  src: string;
  /** Responsive candidates, when the photo has more than one width. */
  srcSet?: string;
  /** The layout width the browser should plan for. */
  sizes?: string;
  /** Published pixel size — reserves the card before the file arrives. */
  width: number;
  height: number;
  /** Describes the photo truthfully; samples say they are samples. */
  alt: string;
  /** A few words under the photo (the reading budget's caption rule). */
  caption: string;
  /** The existing honesty label for illustrative client material. */
  note?: string;
};

export type GalleryGroup = {
  id: string;
  kicker: string;
  heading: string;
  /** One short line; the page's prose budget is measured over these. */
  intro: string;
  photos: readonly GalleryPhoto[];
};

/** Build a srcset from the generated file names (scripts/build-gallery-images.mjs). */
function widthSet(name: string, widths: readonly number[]): string {
  return widths.map((width) => `/media/gallery/${name}-${width}.webp ${width}w`).join(", ");
}

const GATE_NAME = "park-gate";
const PAVILION_NAME = "park-pavilion";

/**
 * The hero photograph — the client's own gate photo (the site's established
 * hero/OG image). Its caption names the sign the photo actually shows.
 */
export const GALLERY_HERO: GalleryPhoto = {
  src: `/media/gallery/${GATE_NAME}-1024.webp`,
  srcSet: widthSet(GATE_NAME, [640, 1024, 1626]),
  sizes: "(max-width: 52rem) 100vw, 44vw",
  width: 1626,
  height: 916,
  alt: "The park's entrance gate, with the stone sign reading Sanctuario de Mercedes y Gloria and the drive behind it",
  caption: "The entrance gate — Sanctuario de Mercedes y Gloria.",
};

/**
 * The one real wide photograph of the grounds, kept apart from the promo
 * composite it was cropped from (see the build script).
 */
export const GALLERY_GROUNDS: GalleryPhoto = {
  src: `/media/gallery/${PAVILION_NAME}-940.webp`,
  srcSet: widthSet(PAVILION_NAME, [640, 940]),
  sizes: "(max-width: 60rem) 100vw, 940px",
  width: 940,
  height: 545,
  alt: "The park's open pavilion and lawn, with visitors on the tiled floor and green hills behind",
  caption: "The pavilion and the grounds, with the hills beyond.",
};

/**
 * The masterplan, shown beside the walk-through entry — the one drawing both
 * park-map modes are built from, captioned as a drawing.
 */
export const GALLERY_MASTERPLAN: GalleryPhoto = {
  src: "/media/gallery/masterplan-480.webp",
  srcSet: widthSet("masterplan", [480, 960]),
  sizes: "(max-width: 62rem) 92vw, 480px",
  width: 960,
  height: 960,
  alt: "The park masterplan: sections, main road, walking paths, mausoleum, garden niches and premium lots drawn to scale",
  caption: "The masterplan.",
  note: "The drawing the park map and the 3D walk-through are built from.",
};

/**
 * The photo groups, in the order the page renders them. Group 1 is the park
 * itself; group 2 is the care that happens in it — the uploaded viewing photo
 * plus the client sheet's three sample set-ups, each keeping the sheet's own
 * "illustration purposes only" discipline.
 */
export const GALLERY_GROUPS: readonly GalleryGroup[] = [
  {
    id: "park",
    kicker: "The park",
    heading: "The grounds and the setting",
    intro: "The park's own photograph of the pavilion and the country around it.",
    photos: [GALLERY_GROUNDS],
  },
  {
    id: "chapels",
    kicker: "Chapels and care",
    heading: "Chapels, viewing and the march",
    intro: "Sample set-ups and service — the office prepares the real one with you.",
    photos: [
      {
        src: "/media/gallery/wake-viewing-420.webp",
        srcSet: widthSet("wake-viewing", [420, 840]),
        sizes: "(max-width: 64rem) 47vw, 19rem",
        width: 840,
        height: 560,
        alt: "A sample wake set-up with the casket, floral arrangements and viewing area prepared",
        caption: "A prepared viewing set-up.",
        note: CHAPEL_SAMPLE_NOTE,
      },
      {
        src: "/media/gallery/chapel-common-300.webp",
        width: 300,
        height: 200,
        alt: "Sample wake set-up in a shared hall, with floral tributes and a covered casket",
        caption: "Common chapel sample.",
        note: CHAPEL_SAMPLE_NOTE,
      },
      {
        src: "/media/gallery/chapel-private-305.webp",
        width: 305,
        height: 203,
        alt: "Sample decorated viewing room with a white casket, a floral arch and candles",
        caption: "Private viewing room sample.",
        note: CHAPEL_SAMPLE_NOTE,
      },
      {
        src: "/media/gallery/service-carriage-419.webp",
        width: 419,
        height: 279,
        alt: "The client's sample funeral carriage on the street, with its gold-panelled casket compartment, glass window and motorcycle front",
        caption: "A sample funeral carriage.",
        note: SERVICE_SAMPLE_NOTE,
      },
    ],
  },
];

/** The straight sentence the page prints beside the walk-through entry. */
export const GALLERY_TOUR_LINE =
  "The map shows where every lot is; 3D moves you through the grounds. Both open from the park page.";

/** The one honest summary of where every photograph on the page came from. */
export const GALLERY_PROVENANCE_NOTE =
  "Every photograph here is the park's own; sample set-ups are labelled.";
