// Tailwind config mirroring the COO's Stitch design tokens
// (stitch_villa_memorial_digital_platform). Named colors = "Serene Legacy"
// defaults (the majority of COO pages). Pages that use the "Luminous"
// home-variant palette override collisions with arbitrary hex values
// (e.g. bg-[#f5faff], bg-[#fdc003]) so every page renders its exact colors.

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // --- Serene Legacy (default page palette) ---
        primary: "#00658d",
        "primary-container": "#00aeef",
        "primary-fixed": "#c6e7ff",
        "primary-fixed-dim": "#82cfff",
        "on-primary": "#ffffff",
        "on-primary-container": "#003e58",
        "on-primary-fixed": "#001e2d",
        "on-primary-fixed-variant": "#004c6b",
        "inverse-primary": "#82cfff",
        secondary: "#735c00",
        "secondary-container": "#fed65b",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#745c00",
        "on-secondary-fixed": "#241a00",
        "on-secondary-fixed-variant": "#574500",
        tertiary: "#5d5f5f",
        "tertiary-container": "#a2a3a3",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#38393a",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        background: "#fbf9f8",
        "on-background": "#1b1c1c",
        surface: "#fbf9f8",
        "surface-bright": "#fbf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e1",
        "surface-variant": "#e4e2e1",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#3e4850",
        outline: "#6e7881",
        "outline-variant": "#bdc8d1",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        // --- Luminous / shared extras ---
        "sky-wash": "#f0f9ff",
        "charcoal-text": "#1b1c1c",
        "serene-blue-deep": "#00658d",
        // Gold used verbatim on the lots catalog CTA
        gold: "#D4AF37",
        "gold-hover": "#c29f32",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "-apple-system", "Segoe UI", "Roboto", "sans-serif"],
        serif: ["Playfair Display", "Georgia", "Times New Roman", "serif"],
        // COO token-name font families (class names used by the mockups)
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        quote: ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        quote: ["24px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      boxShadow: {
        ambient: "0 10px 40px -10px rgba(51,51,51,0.06)",
        "ambient-soft": "0 4px 40px rgba(51,51,51,0.04)",
        ambient2: "0 10px 30px -10px rgba(51,51,51,0.05)",
        card: "0 8px 30px rgb(51 51 51 / 0.06)",
        lift: "0 20px 40px -10px rgba(51,51,51,0.12)",
        "lift-blue": "0 20px 40px -10px rgba(0,101,141,0.1)",
        "soft-shadow": "0 10px 40px -10px rgba(51,51,51,0.06)",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "section-gap": "80px",
      },
    },
  },
  plugins: [],
};
